### PR TITLE
PHP8.2 fixes: Unknown key

### LINKED ISSUE #155: PHP8.2 Errors
I open this issue for _all_ PHP8.2 related problems. (Personally, I test on Debian Bookworm with latest upgrades). Related branch: https://github.com/leibler/dokuwiki-plugin-todo/blob/php8.2

If you find something related, please refer to the appropriate sections here:

### Undefined array key

> Undefined array key "todousers" in /home/dw01/dokuwiki/lib/plugins/todo/syntax/list.php on line 425

https://github.com/leibler/dokuwiki-plugin-todo/blob/4f36f53781bbdb074262766d94d2404836f3e16d/syntax/list.php#L425C8-L425C89

Maybe this could be fixed with  `array_key_exists(string|int $key, array $array): bool` which seems to work:

`if (!$condition2 && is_array($data['assigned']) &&  array_key_exists('todousers', $data)  && is_array($data['todousers']))`

- Would we still need the `is_array($data['todousers'])` check?
- Is this necessary for `$data['assigned']` too?
- Shall we rewrite all `is_array` checks (list.php: 418, 425, 431; todo.php: 421)?
- Maybe it would be sufficient to check with `isset()`?

### PR DESCRIPTION
**Pull request by runout-at**
I finally did stick with the isset() solution for all is_array() occurrences.

this fixes #155

### CODE REVIEW

File: syntax/list.php
Comment (einhirn) [inline syntax/list.php:1]: I've got the feeling that it might be more readable to create an additional function so we don't blow up the `if`'s like this. But I don't know whether Dokuwiki already has those - and if it doesn't I don't think we really need to change this now.

File: syntax/list.php [hunk 1]
```diff
@@ -415,27 +415,27 @@ private function isRequestedTodo($data) {
...
-        if($condition2 && is_array($data['completeduserlist']))
+        if($condition2 && isset($data['completeduserlist']) && is_array($data['completeduserlist']))
             $condition2 = in_array($data['completeduser'], $data['completeduserlist']);
 
         //compare start/due dates
         if($condition1 && $condition2) {
             $condition3s = true; $condition3d = true;
             if(isset($data['startbefore']) || isset($data['startafter']) || isset($data['startat'])) {
-                if(is_object($data['start'])) {
+                if(isset($data['start'])) {
```
Comment (einhirn) [inline syntax/list.php:438]: I'm not sure whether this should rather be `isset && is_object` - but since we don't use `$data['due']` as an Object later on, this probably will be fine.

Comment (runout-at) [reply syntax/list.php:438]: I'm not sure either if a check for the type is necessary.

File: syntax/list.php
Comment (runout-at) [reply syntax/list.php:1]: You're right. And PHP is a mess...
